In [1]:
import numpy as np
X = np.array([
    [1,0,-1],
    [1,0,0],
    [1,0,1],
    [1,0,2],
    [1,0,3],
    [1,1,0],
    [1,2,0],
    [1,2,1]
])
X

array([[ 1,  0, -1],
       [ 1,  0,  0],
       [ 1,  0,  1],
       [ 1,  0,  2],
       [ 1,  0,  3],
       [ 1,  1,  0],
       [ 1,  2,  0],
       [ 1,  2,  1]])

In [23]:
y = np.array([
    [1],
    [-1],
    [1],
    [-1],
    [-1],
    [1],
    [1],
    [1]
])
y

array([[ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [ 1],
       [ 1]])

In [24]:
X.T

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 0,  0,  0,  0,  0,  1,  2,  2],
       [-1,  0,  1,  2,  3,  0,  0,  1]])

In [30]:
B =X.T.dot(X)
B

array([[ 8,  5,  6],
       [ 5,  9,  2],
       [ 6,  2, 16]])

In [31]:
h = X.T.dot(y)
h

array([[ 2],
       [ 5],
       [-4]])

In [33]:
import numpy.linalg as LA
a = LA.inv(B).dot(h)
a

array([[ 0.2248062 ],
       [ 0.51937984],
       [-0.39922481]])

In [34]:
rows = X.shape[0]
for row in range(rows):
    print(row, a.T.dot(X[row,:]))
    

0 [0.62403101]
1 [0.2248062]
2 [-0.1744186]
3 [-0.57364341]
4 [-0.97286822]
5 [0.74418605]
6 [1.26356589]
7 [0.86434109]


In [29]:
y

array([[ 1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [ 1],
       [ 1]])