In [1]:
import numpy as np
B = np.array([[1,2,3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
B.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
X = np.array([[1,0,0], [1, 0, 1], [1, 1, 0],[1, 1, 1]])
X

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [5]:
X.T

array([[1, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 1, 0, 1]])

In [8]:
B = X.T.dot(X)
B

array([[4, 2, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [1]:
import math
print(math.e)

2.718281828459045


In [2]:
math.e**1.1


3.0041660239464334

In [3]:
math.e**0.11

1.1162780704588713